name: API Tests with Postman

on: [push]

jobs:
  test-api:
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Checkout do código
      - name: Checkout do código
        uses: actions/checkout@v3

      # Passo 2: Instala o Node.js
      - name: Instalar o Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.17.0' # Use a versão completa que você está usando

      # Passo 3: Instala o Newman
      - name: Instalar o Newman
        run: npm install -g newman

      # Passo 4: Executa os testes da Collection do Postman
      - name: Executar os testes da Collection do Postman
        run: |
          newman run Serverest.postman_collection.json \
            -e serverestDev.postman_environment.json \
            -g workspace.postman_globals.json \
            --folder "Fluxo completo" \
            --reporters cli
